# Generated by Django 5.0.6 on 2025-01-01 00:00

from django.db import migrations, models
import django.db.models.deletion
import apps.phongtro.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiPhong',
            fields=[
                ('MA_LOAI_PHONG', models.AutoField(primary_key=True, serialize=False)),
                ('TEN_LOAI_PHONG', models.CharField(blank=True, max_length=200, null=True)),
                ('MO_TA_LP', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loaiphong',
            },
        ),
        migrations.CreateModel(
            name='TAISAN',
            fields=[
                ('MA_TAI_SAN', models.IntegerField(primary_key=True, serialize=False)),
                ('TEN_TAI_SAN', models.CharField(blank=True, max_length=100, null=True)),
                ('MO_TA', models.TextField(blank=True, null=True)),
                ('DON_VI_TS', models.CharField(blank=True, default='cái', max_length=20, null=True)),
                ('GIA_TS', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'taisan',
            },
        ),
        migrations.CreateModel(
            name='PhongTro',
            fields=[
                ('MA_PHONG', models.AutoField(primary_key=True, serialize=False)),
                ('TEN_PHONG', models.CharField(blank=True, max_length=200, null=True)),
                ('TRANG_THAI_P', models.CharField(blank=True, max_length=50, null=True)),
                ('GIA_PHONG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('DIEN_TICH', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('SO_NGUOI_TOI_DA', models.IntegerField(blank=True, null=True)),
                ('MO_TA_P', models.TextField(blank=True, null=True)),
                ('SO_TIEN_CAN_COC', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('MA_KHU_VUC', models.IntegerField(db_column='MA_KHU_VUC')),
                ('MA_LOAI_PHONG', models.ForeignKey(db_column='MA_LOAI_PHONG', on_delete=django.db.models.deletion.CASCADE, related_name='ds_phongtro', to='phongtro.loaiphong')),
            ],
            options={
                'db_table': 'phongtro',
            },
        ),
        migrations.CreateModel(
            name='CocPhong',
            fields=[
                ('MA_COC_PHONG', models.AutoField(primary_key=True, serialize=False)),
                ('HO_TEN_TEMP', models.CharField(blank=True, max_length=200, null=True, verbose_name='Họ tên (tạm thời)')),
                ('SO_DIEN_THOAI_TEMP', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại (tạm thời)')),
                ('EMAIL_TEMP', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email (tạm thời)')),
                ('NGAY_COC_PHONG', models.DateField(blank=True, null=True)),
                ('NGAY_DU_KIEN_VAO', models.DateField(blank=True, null=True)),
                ('TIEN_COC_PHONG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('TRANG_THAI_CP', models.CharField(blank=True, choices=[('CHO_XAC_NHAN', 'Chờ xác nhận'), ('DA_XAC_NHAN', 'Đã xác nhận'), ('DA_COC', 'Đã cọc'), ('DA_SU_DUNG', 'Đã sử dụng'), ('DA_HOAN_TRA', 'Đã hoàn trả'), ('DA_THU_HOI', 'Đã thu hồi'), ('DA_TU_CHOI', 'Đã từ chối'), ('DA_HUY', 'Đã hủy')], default='CHO_XAC_NHAN', max_length=50, null=True)),
                ('NGUON_TAO', models.CharField(choices=[('ADMIN', 'Admin tạo'), ('ONLINE', 'Đặt phòng online')], default='ADMIN', max_length=20, verbose_name='Nguồn tạo')),
                ('GHI_CHU_CP', models.TextField(blank=True, null=True)),
                ('LY_DO_TU_CHOI', models.TextField(blank=True, null=True, verbose_name='Lý do từ chối')),
                ('NGAY_TAO', models.DateField(auto_now_add=True, blank=True, null=True, verbose_name='Ngày tạo')),
                ('MA_PHONG', models.IntegerField(db_column='MA_PHONG')),
            ],
            options={
                'verbose_name': 'Cọc phòng / Đặt phòng',
                'verbose_name_plural': 'Cọc phòng / Đặt phòng',
                'db_table': 'cocphong',
                'ordering': ['-NGAY_TAO'],
            },
        ),
        migrations.CreateModel(
            name='TAISANPHONG',
            fields=[
                ('MA_TAI_SAN_PHONG', models.IntegerField(primary_key=True, serialize=False)),
                ('SO_LUONG', models.IntegerField(blank=True, null=True)),
                ('TINH_TRANG', models.CharField(blank=True, max_length=50, null=True)),
                ('NGAY_KIEM_KE', models.DateField(blank=True, null=True)),
                ('GHI_CHU', models.TextField(blank=True, null=True)),
                ('MA_PHONG', models.IntegerField(db_column='MA_PHONG')),
                ('MA_TAI_SAN', models.ForeignKey(db_column='MA_TAI_SAN', null=True, on_delete=django.db.models.deletion.SET_NULL, to='phongtro.taisan')),
            ],
            options={
                'db_table': 'taisanphong',
            },
        ),
        migrations.CreateModel(
            name='TAISANBANGIAO',
            fields=[
                ('MA_BAN_GIAO', models.IntegerField(primary_key=True, serialize=False)),
                ('SO_LUONG', models.IntegerField(blank=True, null=True)),
                ('TINH_TRANG_GIAO', models.CharField(blank=True, max_length=100, null=True)),
                ('GHI_CHU', models.TextField(blank=True, null=True)),
                ('MA_TAI_SAN', models.ForeignKey(db_column='MA_TAI_SAN', null=True, on_delete=django.db.models.deletion.SET_NULL, to='phongtro.taisan')),
            ],
            options={
                'db_table': 'taisanbangiao',
            },
        ),
    ]