# Generated by Django 5.0.6 on 2025-01-02 00:00

from django.db import migrations, models
import django.db.models.deletion
import apps.phongtro.models


class Migration(migrations.Migration):

    dependencies = [
        ('phongtro', '0001_initial'),
    ]

    operations = [
        # Thêm trường MA_KHACH_THUE cho CocPhong (sẽ tạo foreign key sau)
        migrations.AddField(
            model_name='cocphong',
            name='MA_KHACH_THUE',
            field=models.IntegerField(
                db_column='MA_KHACH_THUE',
                null=True,
                blank=True
            ),
        ),
        
        # Thêm trường MA_HOP_DONG cho TAISANBANGIAO (sẽ tạo foreign key sau)
        migrations.AddField(
            model_name='taisanbangiao',
            name='MA_HOP_DONG',
            field=models.IntegerField(
                db_column='MA_HOP_DONG',
                default=1
            ),
            preserve_default=False,
        ),
        
        # Tạo model DangTinPhong
        migrations.CreateModel(
            name='DangTinPhong',
            fields=[
                ('MA_TIN_DANG', models.AutoField(primary_key=True, serialize=False)),
                ('SDT_LIEN_HE', models.CharField(max_length=15, verbose_name='Số điện thoại liên hệ')),
                ('EMAIL_LIEN_HE', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email liên hệ')),
                ('TRANG_THAI', models.CharField(
                    choices=[('DANG_HIEN_THI', 'Đang hiển thị'), ('DA_AN', 'Đã ẩn')],
                    default='DANG_HIEN_THI',
                    max_length=20,
                    verbose_name='Trạng thái'
                )),
                ('NGAY_DANG', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('NGAY_CAP_NHAT', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('LUOT_XEM', models.IntegerField(default=0, verbose_name='Lượt xem')),
                ('LUOT_LIEN_HE', models.IntegerField(default=0, verbose_name='Lượt liên hệ')),
                ('MA_PHONG', models.IntegerField(db_column='MA_PHONG', unique=True)),
            ],
            options={
                'verbose_name': 'Tin đăng phòng',
                'verbose_name_plural': 'Tin đăng phòng',
                'db_table': 'dangtinphong',
                'ordering': ['-NGAY_CAP_NHAT'],
            },
        ),
        
        # Tạo model HinhAnhTinDang
        migrations.CreateModel(
            name='HinhAnhTinDang',
            fields=[
                ('MA_HINH_ANH', models.AutoField(primary_key=True, serialize=False)),
                ('HINH_ANH', models.ImageField(upload_to=apps.phongtro.models.hinh_anh_tin_dang_path, verbose_name='Hình ảnh')),
                ('THU_TU', models.PositiveIntegerField(default=1, verbose_name='Thứ tự hiển thị')),
                ('MO_TA', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mô tả hình ảnh')),
                ('NGAY_TAO', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('MA_TIN_DANG', models.IntegerField(db_column='MA_TIN_DANG')),
            ],
            options={
                'verbose_name': 'Hình ảnh tin đăng',
                'verbose_name_plural': 'Hình ảnh tin đăng',
                'db_table': 'hinhanhtindang',
                'ordering': ['THU_TU'],
            },
        ),
    ]